import { Injectable, inject } from '@angular/core';
import { Store } from '@ngrx/store';
import {
  BehaviorSubject,
  EMPTY,
  Observable,
  catchError,
  combineLatest,
  debounceTime,
  distinctUntilChanged,
  map,
  of,
  scan,
  shareReplay,
  startWith,
  switchMap,
  tap,
} from 'rxjs';

import {
  CRYPTO_PROVIDER,
  CryptoProviderRegistry,
  MarketSortField,
  MarketsQuery,
  SortDirection,
} from '../../core/data';
import {
  CryptoError,
  HistoricalPoint,
  MarketRow,
  Quote,
  Range,
} from '../../core/domain';
import { PrefsActions, prefsFeature } from '../../core/store/prefs';

export interface WatchlistRow extends MarketRow {
  readonly history?: readonly HistoricalPoint[];
}

const HISTORY_RANGE: Range = '7d';

@Injectable()
export class WatchlistState {
  private readonly provider = inject(CRYPTO_PROVIDER);
  private readonly registry = inject(CryptoProviderRegistry);
  private readonly store = inject(Store);

  private readonly searchSubject = new BehaviorSubject<string>('');
  private readonly sortBySubject = new BehaviorSubject<MarketSortField>('marketCap');
  private readonly sortDirSubject = new BehaviorSubject<SortDirection>('desc');

  private readonly loadingSubject = new BehaviorSubject<boolean>(false);
  private readonly errorSubject = new BehaviorSubject<string | null>(null);

  readonly search$ = this.searchSubject.asObservable();
  /** Read directly from the NgRx store — `vsCurrency` is a global preference
   *  that other features (Converter, Wallet) will share. Auto-generated by
   *  `createFeature` from the prefs slice. */
  readonly vsCurrency$ = this.store.select(prefsFeature.selectVsCurrency);
  readonly sortBy$ = this.sortBySubject.asObservable();
  readonly sortDir$ = this.sortDirSubject.asObservable();
  readonly loading$ = this.loadingSubject.asObservable();
  readonly error$ = this.errorSubject.asObservable();

  readonly supportedCurrencies$ = this.provider
    .getSupportedVsCurrencies()
    .pipe(shareReplay({ bufferSize: 1, refCount: true }));

  /**
   * Fetch trigger. The active provider name is included as a third stream
   * not because the query needs it, but to force the downstream switchMap
   * chain to restart when the user picks a different provider — that way
   * getMarkets and liveQuotes both run against the new provider with
   * fresh, provider-specific coin ids (no stale ids leaking into the new
   * source's URLs).
   */
  private readonly fetchQuery$: Observable<MarketsQuery> = combineLatest([
    this.search$.pipe(
      debounceTime(200),
      map((s) => s.trim()),
      distinctUntilChanged(),
    ),
    this.vsCurrency$.pipe(distinctUntilChanged()),
    this.registry.activeName$.pipe(distinctUntilChanged()),
  ]).pipe(
    map(([search, vsCurrency]) => ({
      vsCurrency,
      search,
      pageSize: 25,
      page: 1,
    })),
  );

  /**
   * One getMarkets fetch shared by both the live-quote and history pipelines.
   */
  private readonly initialFetch$ = this.fetchQuery$.pipe(
    tap(() => {
      this.loadingSubject.next(true);
      this.errorSubject.next(null);
    }),
    switchMap((query) =>
      this.provider.getMarkets(query).pipe(
        tap(() => this.loadingSubject.next(false)),
        map((rows) => ({ query, rows })),
        catchError((err) => {
          this.loadingSubject.next(false);
          this.errorSubject.next(toMessage(err));
          return of({ query, rows: [] as MarketRow[] });
        }),
      ),
    ),
    shareReplay({ bufferSize: 1, refCount: true }),
  );

  private readonly rowsWithLive$: Observable<MarketRow[]> = this.initialFetch$.pipe(
    switchMap(({ rows, query }) => {
      const ids = rows.map((r) => r.id);
      if (ids.length === 0) return of(rows);
      return this.provider.liveQuotes(ids, query.vsCurrency).pipe(
        // Defensive: if a provider's live stream terminates with an error,
        // fall back to the static rows so the UI keeps working.
        catchError(() => EMPTY),
        scan((acc, q) => applyQuote(acc, q), rows),
        startWith(rows),
      );
    }),
  );

  /**
   * Per-coin history map keyed by coin id. We only call getHistory for coins
   * whose history was NOT already inlined by the provider in getMarkets — this
   * keeps Mock's behavior (synthesized history per coin) and lets CoinGecko
   * skip those calls entirely thanks to sparkline=true.
   */
  private readonly histories$: Observable<ReadonlyMap<string, readonly HistoricalPoint[]>> =
    this.initialFetch$.pipe(
      switchMap(({ rows, query }) => {
        const inlined = new Map<string, readonly HistoricalPoint[]>();
        const needFetch: MarketRow[] = [];
        for (const r of rows) {
          if (r.history && r.history.length > 0) {
            inlined.set(r.id, r.history);
          } else {
            needFetch.push(r);
          }
        }
        if (needFetch.length === 0) {
          return of(inlined as ReadonlyMap<string, readonly HistoricalPoint[]>);
        }
        const requests = needFetch.map((r) =>
          this.provider.getHistory(r.id, query.vsCurrency, HISTORY_RANGE).pipe(
            map((points) => [r.id, points] as const),
            catchError(() => of([r.id, [] as readonly HistoricalPoint[]] as const)),
          ),
        );
        return combineLatest(requests).pipe(
          map((pairs) => {
            const merged = new Map(inlined);
            for (const [id, pts] of pairs) merged.set(id, pts);
            return merged as ReadonlyMap<string, readonly HistoricalPoint[]>;
          }),
          startWith(inlined as ReadonlyMap<string, readonly HistoricalPoint[]>),
        );
      }),
    );

  readonly rows$: Observable<WatchlistRow[]> = combineLatest([
    this.rowsWithLive$,
    this.histories$,
    this.sortBy$,
    this.sortDir$,
  ]).pipe(
    map(([rows, histories, by, dir]) => {
      const enriched: WatchlistRow[] = rows.map((r) => ({
        ...r,
        history: histories.get(r.id),
      }));
      return sortRows(enriched, by, dir);
    }),
    shareReplay({ bufferSize: 1, refCount: true }),
  );

  /**
   * Currently selected row id (null when nothing is open). The selected row
   * is derived by joining this with rows$ so that live price updates flow
   * straight into the detail panel — no separate subscription needed.
   */
  private readonly selectedIdSubject = new BehaviorSubject<string | null>(null);
  readonly selectedId$ = this.selectedIdSubject.asObservable();

  readonly selectedRow$: Observable<WatchlistRow | null> = combineLatest([
    this.rows$,
    this.selectedId$,
  ]).pipe(
    map(([rows, id]) =>
      id == null ? null : (rows.find((r) => r.id === id) ?? null),
    ),
  );

  setSearch(value: string): void {
    this.searchSubject.next(value);
  }

  setVsCurrency(value: string): void {
    // Dispatched as an action so other features (Converter, Wallet) and
    // any future consumers see the change through the store.
    this.store.dispatch(PrefsActions.setVsCurrency({ vsCurrency: value }));
  }

  select(id: string | null): void {
    if (this.selectedIdSubject.value !== id) this.selectedIdSubject.next(id);
  }

  toggleSort(field: MarketSortField): void {
    if (this.sortBySubject.value === field) {
      this.sortDirSubject.next(this.sortDirSubject.value === 'asc' ? 'desc' : 'asc');
    } else {
      this.sortBySubject.next(field);
      this.sortDirSubject.next(field === 'name' ? 'asc' : 'desc');
    }
  }
}

function applyQuote(rows: readonly MarketRow[], quote: Quote): MarketRow[] {
  let changed = false;
  const next = rows.map((row) => {
    if (row.id !== quote.coinId || row.vsCurrency !== quote.vsCurrency) {
      return row;
    }
    changed = true;
    return {
      ...row,
      price: quote.price,
      marketCap: quote.marketCap ?? row.marketCap,
      circulatingSupply: quote.circulatingSupply ?? row.circulatingSupply,
      change24hPct: quote.change24hPct,
      volume24h: quote.volume24h ?? row.volume24h,
      updatedAt: quote.updatedAt,
    };
  });
  return changed ? next : (rows as MarketRow[]);
}

function sortRows<T extends MarketRow>(
  rows: readonly T[],
  field: MarketSortField,
  dir: SortDirection,
): T[] {
  const mul = dir === 'asc' ? 1 : -1;
  const copy = rows.slice();
  copy.sort((a, b) => {
    const av = pick(a, field);
    const bv = pick(b, field);
    if (av === bv) return 0;
    if (av === undefined) return 1;
    if (bv === undefined) return -1;
    return av < bv ? -1 * mul : 1 * mul;
  });
  return copy;
}

function pick(row: MarketRow, field: MarketSortField): number | string | undefined {
  switch (field) {
    case 'marketCap': return row.marketCap;
    case 'price': return row.price;
    case 'change24hPct': return row.change24hPct;
    case 'name': return row.name.toLowerCase();
  }
}

function toMessage(err: unknown): string {
  if (err instanceof CryptoError) return err.message;
  if (err instanceof Error) return err.message;
  return 'Unknown error';
}
